name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: app/
jobs:
  build:
    name: "Build iOS Apps"
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "11.x"          
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.5"
      - name: Install Dependency
        run: flutter pub get
      - name: Create GoogleService-Info.plist
        env:
          GOOGLE_SERVICE_INFO_PLIST_BASE64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}
        run: echo $GOOGLE_SERVICE_INFO_PLIST_BASE64 | base64 --decode > ./ios/Runner/GoogleService-Info.plist
      - name: Build iOS App
        run: flutter build ios --simulator
      - name: Create google-services.json
        env:
          GOOGLE_SERVICE_JSON_BASE64: ${{ secrets.GOOGLE_SERVICE_JSON_BASE64 }}
        run: echo $GOOGLE_SERVICE_JSON_BASE64 | base64 --decode > ./android/app/google-services.json
      - name: Build Android App
        run: flutter build appbundle --debug
      - name: Test
        run: flutter test